<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Reunions extends \App\Entity\Reunions implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Reunions' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Reunions' . "\0" . 'titre', '' . "\0" . 'App\\Entity\\Reunions' . "\0" . 'contenu', '' . "\0" . 'App\\Entity\\Reunions' . "\0" . 'datetimeReu', '' . "\0" . 'App\\Entity\\Reunions' . "\0" . 'lieuReu', '' . "\0" . 'App\\Entity\\Reunions' . "\0" . 'typeReu', '' . "\0" . 'App\\Entity\\Reunions' . "\0" . 'datetimePost', '' . "\0" . 'App\\Entity\\Reunions' . "\0" . 'user'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Reunions' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Reunions' . "\0" . 'titre', '' . "\0" . 'App\\Entity\\Reunions' . "\0" . 'contenu', '' . "\0" . 'App\\Entity\\Reunions' . "\0" . 'datetimeReu', '' . "\0" . 'App\\Entity\\Reunions' . "\0" . 'lieuReu', '' . "\0" . 'App\\Entity\\Reunions' . "\0" . 'typeReu', '' . "\0" . 'App\\Entity\\Reunions' . "\0" . 'datetimePost', '' . "\0" . 'App\\Entity\\Reunions' . "\0" . 'user'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Reunions $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitre(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitre', []);

        return parent::getTitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitre(string $titre): \App\Entity\Reunions
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitre', [$titre]);

        return parent::setTitre($titre);
    }

    /**
     * {@inheritDoc}
     */
    public function getContenu(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContenu', []);

        return parent::getContenu();
    }

    /**
     * {@inheritDoc}
     */
    public function setContenu(string $contenu): \App\Entity\Reunions
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContenu', [$contenu]);

        return parent::setContenu($contenu);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatetimeReu(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatetimeReu', []);

        return parent::getDatetimeReu();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatetimeReu(\DateTimeInterface $datetimeReu): \App\Entity\Reunions
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatetimeReu', [$datetimeReu]);

        return parent::setDatetimeReu($datetimeReu);
    }

    /**
     * {@inheritDoc}
     */
    public function getLieuReu(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLieuReu', []);

        return parent::getLieuReu();
    }

    /**
     * {@inheritDoc}
     */
    public function setLieuReu(string $lieuReu): \App\Entity\Reunions
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLieuReu', [$lieuReu]);

        return parent::setLieuReu($lieuReu);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeReu(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeReu', []);

        return parent::getTypeReu();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeReu(string $typeReu): \App\Entity\Reunions
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeReu', [$typeReu]);

        return parent::setTypeReu($typeReu);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatetimePost(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatetimePost', []);

        return parent::getDatetimePost();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatetimePost(\DateTimeInterface $datetimePost): \App\Entity\Reunions
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatetimePost', [$datetimePost]);

        return parent::setDatetimePost($datetimePost);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser(): ?\App\Entity\Utilisateurs
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(?\App\Entity\Utilisateurs $user): \App\Entity\Reunions
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

}
