<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKNGKupk\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKNGKupk/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKNGKupk.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKNGKupk\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerKNGKupk\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'KNGKupk',
    'container.build_id' => '12831937',
    'container.build_time' => 1584124861,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKNGKupk');
