<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX7Wx72j\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX7Wx72j/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX7Wx72j.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX7Wx72j\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerX7Wx72j\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'X7Wx72j',
    'container.build_id' => '93d2bc92',
    'container.build_time' => 1584021321,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX7Wx72j');
