<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLAaiRSY\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLAaiRSY/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLAaiRSY.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLAaiRSY\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerLAaiRSY\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'LAaiRSY',
    'container.build_id' => '455caae7',
    'container.build_time' => 1584022199,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLAaiRSY');
